### PR TITLE
Unmarshal `bplist16` with `jlutil`

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
[`jlutil`]() does a much better job in parsing `bplist16` than `NSXPCDecoder`:

- `NSXPCDecoder`
```
✅  208) Name: xpc_connection_call_event_handler
✅  Connection Name: com.apple.nsurlstorage-cache
✅  PID: 17681
✅  Data:
✅  	proxynum => 1
	f => 1
	root => <NSXPCDecoder: 0x7f9da4820600> Container data:
{
  notifyCachedURLResponseBecameFileBacked:filePath:forUUID: (@78) => v@:@@@
}
 OOL XPC data: (none)
```

- `jlutil`
```
✅  285) Name: xpc_connection_call_event_handler
✅  Connection Name: com.apple.nsurlstorage-cache
✅  PID: 17681
✅  Data:
✅  	root =>    0: notifyCachedURLResponseBecameFileBacked:filePath:forUUID:
   1: v@:@@@
   2: 
      0: https://init.itunes.apple.com/bag.xml?ix=6
      1: /Users/user/Library/Caches/com.apple.appstore/CommerceRequestCache
      2: E6EFB3F0-BF6A-4F6B-B8CB-BEDCD2A9A5ED



	proxynum => 1
	f => 1
```

This patch makes `gxpc` use `jlutil` if installed in the host system, falling back to `NSXPCDecoder` otherwise. A fallback from `NSXPCDecoder` to `base64EncodedString` was also added for both `bplist16` and `bplist17`, for when `xpc_connection` is unavailable.

The upstream version of `jlutil` contains some bugs and sometimes outputs corrupted data. I was able to locate and address them with these patches:
- https://github.com/t0rr3sp3dr0/SimPLISTic/commit/7c77f2c4809f6f425a7753aa35aa0b4323b35274
- https://github.com/t0rr3sp3dr0/SimPLISTic/commit/46907d7b2253050f5575f5166c69c3e0af6322dc

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
@NSEcho, done!

**Comment by blacktop** [comment]
You could also implement jlutil in Go. Levin open sourced it. Just saying 😏

**Comment by t0rr3sp3dr0** [comment]
Yeah, but that's over 2000 lines of C that would have to get ported to Go. For now, this is the best I can offer 🙂

**Comment by NSEcho** [comment]
Thanks @t0rr3sp3dr0

**Comment by NSEcho** [comment]
@blacktop love the idea, that sounds like something that is worth implementing as a library

**Pull request merged**
